name: Deploy Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'API/**'  # This will trigger the PHP deployment job
      - 'src/**'   # This will trigger the React app deployment job
      - '!Database.php' #Excude databse file that has database conection information

jobs:
  deploy-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 2

      - name: Check for changes in API/
        id: check_api_changes
        run: |
          if [ "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^API/')" ]; then
            echo "Changes detected in API/"
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected in API/"
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Deploy PHP via FTP
        if: env.changes == 'true'  # Run this step only if there are changes in API/
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./API/"  # Local directory for PHP files
          server-dir: "${{ secrets.FTP_PATH }}/API/"  # Target directory on the FTP server
          exclude: "**/node_modules/**, **/.git/**, **/Database.php"  # Exclude unnecessary files

  deploy-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 2

      - name: Check for changes in src/
        id: check_src_changes
        run: |
          if [ "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^src/')" ]; then
            echo "Changes detected in src/"
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected in src/"
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        if: env.changes == 'true'  # Run this step only if there are changes in src/
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version

      - name: Install dependencies
        if: env.changes == 'true'  # Run this step only if there are changes in src/
        run: npm install
        working-directory: ./src  # Specify the directory where your package.json is located

      - name: Build the React app
        if: env.changes == 'true'  # Run this step only if there are changes in src/
        working-directory: ./src  # Specify the directory where your package.json is located
        run: |
            CI=false npm run build


      - name: Deploy React app via FTP
        if: env.changes == 'true'  # Run this step only if there are changes in src/
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./src/build/"  # Local directory for React build files
          server-dir: "${{ secrets.FTP_PATH }}/"  # Target directory on the FTP server
          exclude: "**/node_modules/**, **/.git/**, **/Database.php"  # Exclude unnecessary files
